### ISSUE TITLE
[refactor] Remove unused files

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#114]

**Comment by rubenquadros** [comment]
Hey @Kaaveh, you mean to remove unused files in the codebase?

**Comment by Kaaveh** [comment]
Hi @rubenquadros 
Precisely, I mean these files that empty right now(Also the autogenerated test classes we don't need if exist).
Do you like to take this issue?


![Screenshot 2023-10-07 at 7 52 34 AM](https://github.com/Kaaveh/ComposeNews/assets/39463024/b26936f1-5ae7-4362-a0c8-5762c2552bd7)

**Comment by rubenquadros** [comment]
Sure @Kaaveh, I can give this a go!
