### ISSUE TITLE
[bugfix] tablet view

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#144]
Fix these UI issues and make Detail screen scrollable

![Image](https://github.com/Kaaveh/ComposeNews/assets/39463024/532a1d99-be32-4ae9-9cf1-fe467fec6ded)

**Comment by utkarsh006** [comment]
@Kaaveh Assign me this issue

**Comment by Kaaveh** [comment]
Here we go! 🙌🏻

**Comment by Kaaveh** [comment]
Hey, @utkarsh006 !
We have decided to create a checkpoint and move on to the KMP. However, we would like to merge your work. Could you please provide an estimate for completing this task?

**Comment by utkarsh006** [comment]
@Kaaveh I will do it soon.

**Comment by utkarsh006** [comment]
@Kaaveh I won't be working on this issue.

**Comment by Kaaveh** [comment]
@utkarsh006 Right, got it!

**Comment by AmirMousavi-Dev** [comment]
Hi Dear Kaaveh
Is it possible to assign this issue to me?
@Kaaveh

**Comment by Kaaveh** [comment]
Yeah, It's Great! 🙌🏻
