### ISSUE TITLE
[optimize] market list

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#145]
Uniform green color with app color palette

![Image](https://github.com/Kaaveh/ComposeNews/assets/39463024/9749d914-5468-458d-a1b8-35794ca7af8a)

**Comment by Kaaveh** [comment]
@mhmd-android please leave a comment here till I can assign this issue to you.

**Comment by mhmd-android** [comment]
well, I'm here to do that :)

**Comment by Kaaveh** [comment]
Done! 🙌🏻

**Comment by Kaaveh** [comment]
Hey, @mhmd-android !
We have decided to create a checkpoint and move on to the KMP. However, we would like to merge your work. Could you please provide an estimate for completing this task?

**Comment by mhmd-android** [comment]
Hey, @Kaaveh 
I'm really sorry that I didn't deliver the task yet.
Unfortunately, I have been very busy these past few days, but I will try to complete the task tonight or tomorrow

**Comment by Kaaveh** [comment]
@mhmd-android Great! 🤩🙌🏻

**Comment by mhmd-android** [comment]
Thankful. I apologize again for the delay🙌🏻
