### ISSUE TITLE
[optimize] round decimal number by 2 digit

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#147]
![Image](https://github.com/Kaaveh/ComposeNews/assets/39463024/20aa33c3-1267-4df7-8e38-17175500092b)

**Comment by mhmd-android** [comment]
Hey, dear Kaaveh, is this issue assigned to anyone?

**Comment by Kaaveh** [comment]
Hi,
No, do you like to work on it?

**Comment by Kaaveh** [comment]
Also, there is a task about its color to match the Dynamic color of other parts of the UI. I think you are the best candidate for doing that task.

**Comment by mhmd-android** [comment]
Yes, I do both of them, sure
Which parts don't exactly match the dynamic color?

**Comment by mhmd-android** [comment]
I saw, this issue #145

**Comment by Kaaveh** [comment]
> I saw, this issue #145

Exactly, feel free to choose best colors for them! ✌🏻
