### ISSUE TITLE
[bugfix] ci

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#150]
.github/workflows/ci.yaml: No jobs were run
[Error: .github#L1](https://github.com/Kaaveh/ComposeNews/commit/3f81f1a053d779fc1757ec1789ec55b619469ddc#annotation_15082903017)
the `uses' attribute must be a path, a Docker image, or owner/repo@ref

.github/workflows/dependabot.yml: No jobs were run
[Error: .github#L1](https://github.com/Kaaveh/ComposeNews/commit/3f81f1a053d779fc1757ec1789ec55b619469ddc#annotation_15082903000)
No event triggers defined in `on`

**Comment by Amnish04** [comment]
Hi @Kaaveh, could you share more details
