### ISSUE TITLE
Skeleton for Detail screen

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#161]
![Screenshot_20231027_071049](https://github.com/Kaaveh/ComposeNews/assets/39463024/00ae5894-f543-4586-8f5d-c71d709b4aff)

**Comment by hadi-norouzi** [comment]
Could you please assign it to me?

**Comment by Kaaveh** [comment]
Sure! I'm glad we have you! 🙌🏻
