### ISSUE TITLE
Code generation for large screen preview

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#169]
According to our conversion in #166

**Comment by mhmd-android** [comment]
Hi, I'm here to take it  🤚

**Comment by Kaaveh** [comment]
Hey @mhmd-android,
Do you have any updates on this task?

**Comment by mhmd-android** [comment]
Hey @Kaaveh
Unfortunately, I didn't have enough time to work on this issue, but I will definitely take care of it as soon as possible

**Comment by Kaaveh** [comment]
Great, thanks @mhmd-android

**Comment by mhmd-android** [comment]
Hi dear @Kaaveh 

After a thorough review of the proposed solution to use code generation to address the current issue in the ComposeNews project, I've concluded that this approach might not be the best solution for several reasons:

**Limited Utility**: While the idea of using a code generator for this specific problem might seem appealing, the truth is that its application would be limited to this particular case only, offering no reusability in other parts of the project or future projects.

**Unnecessary Complexity**: Introducing a code generation layer into the project could add unwanted complexity. This complexity might complicate code maintenance and understanding for other developers, especially those new to the project.

**Focus on More Pragmatic Solutions**: It would be more beneficial to explore solutions that enhance the code's maintainability and readability without introducing additional layers that might not add significant value.

Thank you for considering my perspective on this matter.

**Comment by Kaaveh** [comment]
@mhmd-android No problem, I think we can close this issue 👍
