### ISSUE TITLE
Crash on switching btw BottomBar tabs

### ISSUE THREAD

**Issue by jalalaghazadeh** [Kaaveh/ComposeNews#185]
A crash can happen when you switch btw button-bar tabs several times.
here is a StackTrace:

```FATAL EXCEPTION: main
Process: ir.composenews, PID: 8708
retrofit2.HttpException: HTTP 429 
at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4ef69d2, Dispatchers.Main.immediate]```

**Comment by Kaaveh** [comment]
Hey @jalalaghazadeh , Thanks a lot for reporting!
Are you willing to working on this issue?

**Comment by jalalaghazadeh** [comment]
> Hey @jalalaghazadeh , Thanks a lot for reporting!
> Are you willing to working on this issue?

Hey @Kaaveh , that would be my pleasure. I'll send a MR asap.

**Comment by Kaaveh** [comment]
@jalalaghazadeh Awesome! I'll assign this issue to you! 🙌🏻

**Comment by Kaaveh** [comment]
Hey @jalalaghazadeh 
Do you have any updates on this task?

**Comment by jalalaghazadeh** [comment]
> Hey @jalalaghazadeh Do you have any updates on this task?

I did some debugging on the matter and it was due to not handling http exceptions in which can be handled in a interceptor in process of building OkHttpClient object. there was a lot going on and I lost track of this one :(
