### ISSUE TITLE
[test] MarketModelMapper.kt

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#187]
Write test for [`MarketModelMapper.kt`](https://github.com/Kaaveh/ComposeNews/blob/kmp/core/uimarket/src/main/java/ir/composenews/uimarket/mapper/MarketModelMapper.kt) methods

**Comment by abbasiandev** [comment]
assign me please

**Comment by Kaaveh** [comment]
Hey @MahdiAbbasian,
Do you have any updates on this task?
