### ISSUE TITLE
Can not reach to the API service

### ISSUE THREAD

**Issue by rezazarchi** [Kaaveh/ComposeNews#216]
I've been experiencing issues when trying to reach the API endpoint at `api.coingecko.com` while running the project. It appears that there might be a server-side issue.
Please review this issue.
Thank you!

**Comment by Kaaveh** [comment]
Hey @rezazarchi , Thanks for your feedback! 🙌🏻
Would you like to work on issue?

**Comment by rezazarchi** [comment]
According to status.coingecko.com the server is up now. It might be a temporary issue. Now is up and I can now work on my own [issue](https://github.com/Kaaveh/ComposeNews/issues/176) 😇

**Comment by Kaaveh** [comment]
Excellent! 🙌🏻
