### ISSUE TITLE
[refactor] adaptive layout

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#217]
Refactor existing adaptive layouts in line with the latest update of Material3 Adaptive Layout and best practices.

Sample:
https://www.youtube.com/watch?v=v6PuClhFfTc

**Comment by rezazarchi** [comment]
I've set up a [test project](https://github.com/rezazarchi/AdaptiveUI) using these resources: [Link 1](https://developer.android.com/develop/ui/compose/layouts/adaptive/list-detail), [Link 2](https://developer.android.com/develop/ui/compose/layouts/adaptive/build-adaptive-navigation), [Link 3](https://youtu.be/u8vQgmgf3X4?si=NJkAM56kp_vZKNfh), and [Link 4](https://youtu.be/W3R_ETKMj0E?si=LTpTDtcjNMGNNBxh). I found it pretty straightforward to implement and think we could migrate to this architecture quickly.

However, I'm a bit concerned about its compatibility with KMP in the future. As you can see in the official KMP [article](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-navigation-routing.html), even Jetpack Navigation is still under development. This new approach is even more complex.

By the way, If you're interested in having this implementation in the project, , I'd be happy to help out!
