### ISSUE TITLE
[Feature Request] Add CI/CD pipeline to the repository

### ISSUE THREAD

**Issue by MohammadSianaki** [Kaaveh/ComposeNews#44]

**Comment by Kaaveh** [comment]
Good idea!
If you like to work on it, don't be shy! 😉✌🏻

**Comment by MohammadSianaki** [comment]
I'd love to, but I don't have the right access

**Comment by Kaaveh** [comment]
I invited you as collaborator. Please check your email.

**Comment by MohammadSianaki** [comment]
This PR addresses this issue. So I will close this issue
