### ISSUE TITLE
[Discussion] Coupling codes when using base classes

### ISSUE THREAD

**Issue by nero240399** [Kaaveh/ComposeNews#48]
I think we shouldn't use base classes like: BaseContract, BaseScreen and BaseViewModel.
Just keep it separated like in the medium article.
Maybe those base classes all work in the current codebase but when it is expanded, we will be confused to use they or not and use for what.

**Comment by Kaaveh** [comment]
Yes, I agree with you! In my opinion, it's very dependent on code-base conditions.
Thanks for sharing your idea! ❤️
