### ISSUE TITLE
Tablet & foldable view

### ISSUE THREAD

**Issue by MohammadRezaei92** [Kaaveh/ComposeNews#51]
Hi
I do some research about adaptive views in Jetpack Compose. So I think I know how to do this task. If it's Ok I'm ready to do that.

**Comment by Kaaveh** [comment]
Sure, go for it! ❤️✌🏻

**Comment by Kaaveh** [comment]
Hi @MohammadRezaei92 
Any progress on this task?

**Comment by MohammadRezaei92** [comment]
Hi @Kaaveh 
I've done about 60% of this task, but unfortunately, I'm a bit busy now 🙈. I will do it ASAP.

**Comment by Kaaveh** [comment]
@MohammadRezaei92 
Excellent! 😍 I'm eagerly waiting for your PR! ✌🏻
